spring.application.name=horizontemeu

# ─── Banco de dados Neon (PostgreSQL) ─────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://ep-twilight-cloud-ac1h0hy1-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JNDw1haKx7Qo
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA / Hibernate ──────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ─── JWT ──────────────────────────────────────────────────────────────────────
jwt.secret=horizonte-meu-chave-secreta-super-segura-2025
jwt.expiration-ms=86400000

cloudinary.cloud-name=demaptbvn
cloudinary.api-key=739172427458169
cloudinary.api-secret=YG58yj3NUD6L-_ojgKPqWGCVSwc


resend.api.key=${RESEND_API_KEY}
resend.from.email=${RESEND_FROM_EMAIL}